name: pulse-notification-backend
region: sgp
services:
  - name: notification-server
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    instance_count: 1
    instance_size_slug: basic-xxs
    source_dir: /pulse_notification_backendd
    build_command: npm install
    run_command: npm start
    http_port: 3000
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
        type: GENERAL
      - key: PORT
        value: "3000"
        scope: RUN_TIME
        type: GENERAL
      - key: FIREBASE_DATABASE_URL
        value: https://pulse-app-ea5be-default-rtdb.asia-southeast1.firebasedatabase.app
        scope: RUN_TIME
        type: GENERAL
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        scope: RUN_TIME
        type: SECRET